@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package jakojaannos.sgbswspmc.bloodmagic.criterion;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;